<?
	/**
	 * generate a new entry for a database table
	 * i do not care about the structure or name of this table
	 */

	$this->set('title', 'Add new entry for '.$model);
	$this->addJavascriptFile('/js/tiny_mce.js');
	$this->addJavascriptFile('/js/tiny_mce_init.js');
?>

<h1><?= $this->get('title') ?></h1>

<a href="/admin/listing/<?= $model ?>"><?= ucfirst($model) ?>-Overview</a> 
<hr />

<form action="" method="post">
	<table>
		<tr>
			<th>Key</th>
			<th>Value</th>
			<th>Default</th>
		</tr>
		<? foreach($columns as $column): ?>
			<tr>
				<td>
					<?= $column->COLUMN_NAME ?><br />
					<small>(<?= $column->DATA_TYPE ?>)</small>
				</td>
				<td>
					<? if($column->COLUMN_NAME == 'id'): ?>
						<input disabled="disabled" type="text" /><br />
						<small>IDs are generated by database!</small>
					<? elseif(strstr($column->COLUMN_NAME, 'is_')): ?>
						<input value="1" type="checkbox" <?= $column->COLUMN_DEFAULT == '1'? 'checked="checked"' : '' ?> name="adddata[<?= $column->COLUMN_NAME ?>]" />
					<? elseif(in_array($column->COLUMN_NAME, array('pass', 'password', 'passwort'))): ?>
						<input type="password" name="adddata[<?= $column->COLUMN_NAME ?>]" />
					<? elseif(in_array($column->DATA_TYPE, array('datetime'))): ?>
						<input type="text" name="adddata[<?= $column->COLUMN_NAME ?>]" value="<?= Helper::getDate() ?>" />
					<? elseif(in_array($column->DATA_TYPE, array('tinyint', 'varchar', 'int'))): ?>
						<input type="text" name="adddata[<?= $column->COLUMN_NAME ?>]" />
					<? elseif(in_array($column->DATA_TYPE, array('text'))): ?>
						<textarea rows="1000" cols="1000" name="adddata[<?= $column->COLUMN_NAME ?>]"></textarea>
					<? endif ?>
				</td>
				<td>
					<span style="font-weight: bold;">
						<? if(null === $column->COLUMN_DEFAULT): ?>
							null
						<? else: ?>
							<?= $column->COLUMN_DEFAULT ?>
						<? endif ?>
					</span>
				</td>
			</tr>
		<? endforeach ?>
		<tr>
			<td>&nbsp;</td>
			<td>
				<input type="submit" value="add" />
			</td>
			<td>&nbsp;</td>
		</tr>
	</table>
</form>